services:
  - type: web
    name: bitespeed-identity-api
    env: node
    buildCommand: npm install && npx prisma generate --schema=./prisma/schema.prisma && npm run build
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
    envVars:
      - key: NODE_ENV
        value: production
