services:
  - type: web
    name: bitespeed-identity-api
    env: node
    buildCommand: npm install && npx prisma generate --schema=./prisma/schema.prisma && npm run build
    startCommand: npx prisma migrate deploy --schema=./prisma/schema.prisma && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/data/sqlite.db
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
